### ISSUE TITLE
How to get instance IP when the status is OK

### ISSUE THREAD

**Issue by xueyilong** [maxwo/snmp_notifier#100]
I get the instance ip with parameter --snmp.extra-field-template=4=/opt/snmp_notifier/extra-field-template.tpl ,and it effective only when the alert is active,  now i want the ip with alert resolve
 
my extra-field-template.tpl file like:
{{- if .Alerts -}}
{{- range $severity, $alerts := (groupAlertsByLabel .Alerts "severity") -}}
{{- range $index, $alert := $alerts }}
{{ $alert.Annotations.ip }}
{{ end }}
{{ end }}
{{ else -}}
127.0.0.1
{{- end -}}

127.0.0.1 is not the real alert instance ip .

<img width="1049" alt="wecom-temp-32f0f643bec4001ba6447ccb6b0a98c2" src="https://user-images.githubusercontent.com/20434574/152919376-322d7fe4-6366-421e-b247-133ae90ca327.png">

**Comment by travelliu** [comment]
@maxwo 
```
		if alert.Status == "firing" {
			err = alertParser.addAlertToGroup(alertGroups[key], alert)
			if err != nil {
				return nil, err
			}
		}
```
Whether alert.Status filtering can be canceled

**Comment by maxwo** [comment]
Your case can now be handled thanks to this PR: https://github.com/maxwo/snmp_notifier/pull/122

It adds a `.DeclaredAlerts` variable in the template, so that you can access any label/info of the declared alerts, even if they are not firing.
