### ISSUE TITLE
level=error msg="400 Bad Request

### ISSUE THREAD

**Issue by B-Betty** [maxwo/snmp_notifier#111]
### Alertmanager configuration file:
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitor
data:
  alertmanager.yml: |-
    global:
    route:
      group_by: ['alertname']
      group_wait: 30s
      group_interval: 30s
      repeat_interval: 30s
      receiver: 'snmp_notifier'
    receivers:
    - name: 'snmp_notifier'
      webhook_configs:
      - send_resolved: true
        url: http://nodeIp:9464/alerts
    inhibit_rules:
      - source_match:
          severity: 'critical'
        target_match:
          severity: 'warning'
        equal: ['alertname', 'dev', 'instance'] 
prometheus configuration file:
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitor
data:
  prometheus.yml: |
    global:
      scrape_interval:     20s # 抓取周期
      evaluation_interval: 20s # 估算规则的周期
    rule_files:
    - /etc/config/rules/*.rules
    scrape_configs:
    - job_name: "otel-collector"
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_pod_container_port_number]
        action: keep
        regex: monitor;8889
      - source_labels: [__meta_kubernetes_pod_node_name]
        action: replace
        target_label: kubernetes_node_name
    - job_name: prometheus
      static_configs:
      - targets:
        - localhost:9090
    alerting:
      alertmanagers:
      - static_configs:
          - targets: ["alertmanager.monitor:9093"] 
          
### start up snmp_notifier
--download
https://github.com/maxwo/snmp_notifier/releases/download/v1.2.1/snmp_notifier-1.2.1.linux-amd64.tar.gz
--start up snmp_notifier
# tar -zxvf snmp_notifier-1.2.1.linux-amd64.tar.gz -C /opt
# mv /opt/snmp_notifier-1.2.1.linux-amd64 /opt/snmp_notifier
# cd /opt/snmp_notifier
# nohup /opt/snmp_notifier/snmp_notifier > /opt/snmp_notifier/snmp_notifier.log 2>&1 &
# netstat -nap |grep -i 9464
tcp6       0      0 :::9464                 :::*                    LISTEN      14502/snmp_notifier

### logs
but. alert manager can not send alert to snmp_notifier, alert manager logs:
ts=2022-06-08T07:12:12.798Z caller=dispatch.go:354 level=error component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="snmp_notifier/webhook[0]: notify retry canceled due to unrecoverable error after 1 attempts: unexpected status code 400: http://10.99.212.66:9464/alerts"
ts=2022-06-08T07:12:42.801Z caller=dispatch.go:354 level=error component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="snmp_notifier/webhook[0]: notify retry canceled due to unrecoverable error after 1 attempts: unexpected status code 400: http://10.99.212.66:9464/alerts"
ts=2022-06-08T07:13:12.803Z caller=dispatch.go:354 level=error component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="snmp_notifier/webhook[0]: notify retry canceled due to unrecoverable error after 1 attempts: unexpected status code 400: http://10.99.212.66:9464/alerts"
ts=2022-06-08T07:13:42.801Z caller=dispatch.go:354 level=error component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="snmp_notifier/webhook[0]: notify retry canceled due to unrecoverable error after 1 attempts: unexpected status code 400: http://10.99.212.66:9464/alerts"
ts=2022-06-08T07:14:12.803Z caller=dispatch.go:354 level=error component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="snmp_notifier/webhook[0]: notify retry canceled due to unrecoverable error after 1 attempts: unexpected status code 400: http://10.99.212.66:9464/alerts"
ts=2022-06-08T07:14:42.803Z caller=dispatch.go:354 level=error component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="snmp_notifier/webhook[0]: notify retry canceled due to unrecoverable error after 1 attempts: unexpected status code 400: http://10.99.212.66:9464/alerts" 

 
while snmp_notifier.logs as follows:
time="2022-06-08T15:14:12+08:00" level=error msg="400 Bad Request: err=incorrect severity: emergency data=&{Receiver:snmp_notifier Status:firing Alerts:[{Status:firing Labels:map[alertname:NodeMemoryUsage-emergency app_kubernetes_io_component:exporter app_kubernetes_io_name:node-exporter app_kubernetes_io_part_of:kube-prometheus app_kubernetes_io_version:1.3.1 controller_revision_hash:7f4f979f8 http_scheme:http instance:177.177.48.249:8889 job:otel-collector kubernetes_node_name:node66 kubernetes_pod_name:node-exporter-5tg42 net_host_name:177.177.48.210 net_host_port:9100 oid:1.3.6.1.4.1.98789.0.1 pod_template_generation:1 service:node service_instance_id:177.177.48.210:9100 service_name:nodeExporter severity:emergency type:service] Annotations:map[summary:177.177.48.249:8889内存使用大于85% (当前值: 31.021082537787933)] StartsAt:2022-06-08 06:38:32.77 +0000 UTC EndsAt:0001-01-01 00:00:00 +0000 UTC GeneratorURL:http://prometheus-6f7f6bbff4-8sqkv:9090/graph?g0.expr=100+-+%28node_memory_MemFree_bytes%7Bk8scluster%21~%22.%2B%22%7D+%2B+node_memory_Cached_bytes+%2B+node_memory_Buffers_bytes%29+%2F+node_memory_MemTotal_bytes+%2A+100+%3E+15&g0.tab=1 Fingerprint:a417884b87061093}] GroupLabels:map[alertname:NodeMemoryUsage-emergency] CommonLabels:map[alertname:NodeMemoryUsage-emergency app_kubernetes_io_component:exporter app_kubernetes_io_name:node-exporter app_kubernetes_io_part_of:kube-prometheus app_kubernetes_io_version:1.3.1 controller_revision_hash:7f4f979f8 http_scheme:http instance:177.177.48.249:8889 job:otel-collector kubernetes_node_name:node66 kubernetes_pod_name:node-exporter-5tg42 net_host_name:177.177.48.210 net_host_port:9100 oid:1.3.6.1.4.1.98789.0.1 pod_template_generation:1 service:node service_instance_id:177.177.48.210:9100 service_name:nodeExporter severity:emergency type:service] CommonAnnotations:map[summary:177.177.48.249:8889内存使用大于85% (当前值: 31.021082537787933)] ExternalURL:http://alertmanager-69494b9c76-jwgrq:9093}" source="http_server.go:129"
177.177.48.227 - - [08/Jun/2022:15:14:12 +0800] "POST /alerts HTTP/1.1" 400 69
177.177.48.227 - - [08/Jun/2022:15:14:12 +0800] "POST /alerts HTTP/1.1" 200 0
177.177.48.227 - - [08/Jun/2022:15:14:12 +0800] "POST /alerts HTTP/1.1" 200 0
time="2022-06-08T15:14:42+08:00" level=error msg="400 Bad Request: err=incorrect severity: emergency data=&{Receiver:snmp_notifier Status:firing Alerts:[{Status:firing Labels:map[alertname:NodeMemoryUsage-emergency app_kubernetes_io_component:exporter app_kubernetes_io_name:node-exporter app_kubernetes_io_part_of:kube-prometheus app_kubernetes_io_version:1.3.1 controller_revision_hash:7f4f979f8 http_scheme:http instance:177.177.48.249:8889 job:otel-collector kubernetes_node_name:node66 kubernetes_pod_name:node-exporter-5tg42 net_host_name:177.177.48.210 net_host_port:9100 oid:1.3.6.1.4.1.98789.0.1 pod_template_generation:1 service:node service_instance_id:177.177.48.210:9100 service_name:nodeExporter severity:emergency type:service] Annotations:map[summary:177.177.48.249:8889内存使用大于85% (当前值: 31.143249075185608)] StartsAt:2022-06-08 06:38:32.77 +0000 UTC EndsAt:0001-01-01 00:00:00 +0000 UTC GeneratorURL:http://prometheus-6f7f6bbff4-8sqkv:9090/graph?g0.expr=100+-+%28node_memory_MemFree_bytes%7Bk8scluster%21~%22.%2B%22%7D+%2B+node_memory_Cached_bytes+%2B+node_memory_Buffers_bytes%29+%2F+node_memory_MemTotal_bytes+%2A+100+%3E+15&g0.tab=1 Fingerprint:a417884b87061093}] GroupLabels:map[alertname:NodeMemoryUsage-emergency] CommonLabels:map[alertname:NodeMemoryUsage-emergency app_kubernetes_io_component:exporter app_kubernetes_io_name:node-exporter app_kubernetes_io_part_of:kube-prometheus app_kubernetes_io_version:1.3.1 controller_revision_hash:7f4f979f8 http_scheme:http instance:177.177.48.249:8889 job:otel-collector kubernetes_node_name:node66 kubernetes_pod_name:node-exporter-5tg42 net_host_name:177.177.48.210 net_host_port:9100 oid:1.3.6.1.4.1.98789.0.1 pod_template_generation:1 service:node service_instance_id:177.177.48.210:9100 service_name:nodeExporter severity:emergency type:service] CommonAnnotations:map[summary:177.177.48.249:8889内存使用大于85% (当前值: 31.143249075185608)] ExternalURL:http://alertmanager-69494b9c76-jwgrq:9093}" source="http_server.go:129"
177.177.48.227 - - [08/Jun/2022:15:14:42 +0800] "POST /alerts HTTP/1.1" 400 69

what's wrong with my configuration? how can I solve this problem?
thanks very much

**Comment by nbrannigan** [comment]
Hello, any new regarding this issue? I have exactly the same problem. Thank you

**Comment by maxwo** [comment]
I see your alerts contains the `emergency` severity, which is not known by default.

You should pass it through the following option: `--alert.severities="emergency,critical,warning,info"`

Note that they should be listed from the most critical, to the less critical.
