### ISSUE TITLE
Editing the description-template.tpl  file for more fields

### ISSUE THREAD

**Issue by fatihmtekin** [maxwo/snmp_notifier#140]
Hello,

I can get snmp trap packet from snmp_notifier. However, there are 3 field in the file. I added below the output, the 3rd field includes the Status , -Alert, Summary and Description information. I want to separate these fields parametrically. For example, the 4th field is Status, 5th field is -Alert, 6th field is Summary etc.

How can I edit the snmp_notifier template file ( --snmp.extra-field-template=4=alert-count.tpl ) for that configuration?

Could you please guide me?

Many thanks in advance.

* SNMP notifier command line:
```
./snmp_notifier --web.listen-address=:9464 --alert.severities="critical,warning,info" --log.level=debug --snmp.destination=10.110.24.25:162
```

[1] .1.3.6.1.4.1.123.0.10.1.1.1.5.1.2.1 (OctetString): 1.3.6.1.4.1.123.0.10.1.1.1.5.1[]
[2] .1.3.6.1.4.1.123.0.10.1.1.1.5.1.2.2 (OctetString): critical
[3] .1.3.6.1.4.1.123.0.10.1.1.1.5.1.2.3 (OctetString): 1/1 alerts are firing:

Status: critical
- Alert: PostgreSQLInstanceUpDown
Summary: PostgreSQL Instance berlin03 down
Description: berlin03 of job postgres has been down for more than 1 minutes.

**Comment by maxwo** [comment]
Hi,

You should check the default template:

```
{{- if .Alerts -}}
{{ len .Alerts }}/{{ len .DeclaredAlerts }} alerts are firing:

{{ range $severity, $alerts := (groupAlertsByLabel .Alerts "severity") -}}
Status: {{ $severity }}

{{- range $index, $alert := $alerts }}
- Alert: {{ $alert.Labels.alertname }}
  Summary: {{ $alert.Annotations.summary }}
  Description: {{ $alert.Annotations.description }}
{{ end }}
{{ end }}
{{ else -}}
Status: OK
{{- end -}}
```

As you can see, an `Alerts` variable contains the firing alerts, and the `DeclaredAlerts` contains all alerts for this group.

You can therefore reuse the previous template to output only what you are interested in. The used language is the golang template, which is fully documented here: https://pkg.go.dev/text/template

How many alerts per group do you have?

**Comment by mencutekin** [comment]
I have only 1 alert, a postgresql instance up-down alert.
I need to learn go lang :) 
thank you for your help
