### ISSUE TITLE
How to configure the SNMP destination during runtime? Is there any REST API provided by SNMP Notifier?

### ISSUE THREAD

**Issue by bsomani** [maxwo/snmp_notifier#157]
**What did you do?**
I want to configure the snmp server destination during runtime of pod in K8s
**What did you expect to see?**
Is there any restapi provided ? or any other way to configure during runtime
**What did you see instead? Under which circumstances?**
I did not find any documentation to achieve this
**Environment**
K8s, started snmp_notifier through helm
* System information:
linux
	insert output of `uname -srm` here

* SNMP notifier version:
latest
	insert output of `snmp_notifier --version` here

* Alertmanager version:
latest
	insert output of `alertmanager --version` here

* Prometheus version:
latest
	insert output of `prometheus -version` here (if relevant to the issue)

* Alertmanager command line:
```
insert command line here
```

* SNMP notifier command line:
```
insert command line here
```

* Prometheus alert file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
insert logs relevant to the issue here
```

**Comment by maxwo** [comment]
Hello,
These is no way right now to update configuration during runtime. Given the image relies on environment variables & command-line, your deployment/pods should be updated as soon as there is a configuration change.
