### ISSUE TITLE
Release new version to get newer docker image

### ISSUE THREAD

**Issue by falk-w** [maxwo/snmp_notifier#208]
I see a new main image got built after [v1.5.0](https://hub.docker.com/layers/maxwo/snmp-notifier/v1.5.0/images/sha256-c33873b9932a8c3451ba52bbd2d30aaaa5e44e434b466713bcbe3248a7253965?context=explore) has been built quite a while ago (10 months).

Would it be possible to bump the version also to get a newer docker image? (Your Go Bump had some security fixes e.g. https://github.com/golang/go/issues/67680 and I'd like to see them in an image that can be referenced in the official helm chart - https://github.com/prometheus-community/helm-charts/tree/main/charts/alertmanager-snmp-notifier )

**Comment by maxwo** [comment]
Good point indeed. I just released the [v1.5.1](https://github.com/maxwo/snmp_notifier/releases/tag/v1.5.1) that uses the latest Golang images.

I will update the chart to reference that new version. Until then, you can customize the `image.tag` value of the current chart to take it into account.

**Comment by falk-w** [comment]
> Good point indeed. I just released the [v1.6.0](https://github.com/maxwo/snmp_notifier/releases/tag/v1.6.0) that uses the latest Golang images.
> 
> ```
> $ docker run maxwo/snmp-notifier:v1.6.0 --version
> snmp_notifier, version 1.6.0 (branch: HEAD, revision: a7a4593a9db0b46746403d0d338518111a0aabc8)
>   build user:       root@e85efbf57b23
>   build date:       20240929-08:25:40
>   go version:       go1.23.1
>   platform:         linux/arm64
>   tags:             netgo
> ```
> 
> I will update the chart to reference that new version. Until then, you can customize the `image.tag` value of the current chart to take it into account.

Thanks! FYI: The chart automatically uses the appversion so if the appversion is bumped, it should be sufficient!

**Comment by maxwo** [comment]
Yes, but I was willing to add another feature in the chart. I will do a simple PR just for the appVersion.

**Comment by maxwo** [comment]
Helm chart PR: https://github.com/prometheus-community/helm-charts/pull/4893

Needs to be merged, but that ends that issue. Thank you

**Comment by maxwo** [comment]
FYI, Helm Chart PR has been merged.

**Comment by falk-w** [comment]
> FYI, Helm Chart PR has been merged.

Thanks! I was also monitoring this, great work!
