### ISSUE TITLE
[snmp_notifier] Support for Helm

### ISSUE THREAD

**Issue by stevebail** [maxwo/snmp_notifier#22]
Bonjour Maxime,
Any plans to support a helm chart for SNMP notifier?
Merci!

**Comment by maxwo** [comment]
Hi Steve,
There is currently no Helm chart associated, although this is a nice idea for fast deployment.
Will have a look at this, thanks.

**Comment by maxwo** [comment]
A Helm chart is available at that address: https://github.com/maxwo/snmp-notifier-helm-chart 

I will create the PR to add it to the prometheus-community helm charts.
