### ISSUE TITLE
snmp_notifier does not forward tag information of alertmanager alerts

### ISSUE THREAD

**Issue by gitxbillhub** [maxwo/snmp_notifier#49]
Following is the captured snmp trap with snmptrapd service

> iso.3.6.1.2.1.1.3.0 = Timeticks: (11256000) 1 day, 7:16:00.00   iso.3.6.1.6.3.1.1.4.1.0 = OID: iso.3.6.1.4.1.98789.0.1  iso.3.6.1.4.1.98789.0.1.1 = STRING: "1.3.6.1.4.1.98789.0.1[alertname=node_filesystem_free_bytes]" iso.3.6.1.4.1.98789.0.1.2 = STRING: "warning"   iso.3.6.1.4.1.98789.0.1.3 = STRING: "Status: warning
> Alert: node_filesystem_free_bytes
  Summary: Test Alert from Prometheus
  Description: This is a test alert from Prometheus"

I also attach the alertmanager alert snapshot from alertmanager gui. As we can see. the snmp trap lose all the labels information
![alertmanager](https://user-images.githubusercontent.com/16496090/92663461-5e273000-f2cf-11ea-9ed1-654b43e1bc24.png)

**Comment by maxwo** [comment]
Indeed, by default, the description does not contain any tag. But you may change the template to display them if necessary.
