### ISSUE TITLE
Traps are not sent to SNMP Trap listener  in 1.0

### ISSUE THREAD

**Issue by Tilden18** [maxwo/snmp_notifier#56]
**What did you do?**
We are trying to forward the Prometheus Alert Manager Alerts to SNMP Agent Via this Maxwo/snmp_notifier. 
We downloaded the binary from release history page. Version snmp_notifier-1.0.0.linux-amd64.tar.gz 

Alerts are process / received by SNMP Notifier, but it is not sent to the SNMP Trap listener agent. 

[xxxxxr@jumphost snmp_notifier-1.0.0.linux-amd64]$ ./snmp_notifier --snmp.trap-description-template=description-template.tpl --snmp.destination=x.x.x.x:162 
INFO[0000] Preparing to listen on:  :9464                source="http_server.go:104"
10.0.x.x - - [03/Dec/2020:09:41:09 -0500] "POST /alerts HTTP/1.1" 200 0
10.0.x.x - - [03/Dec/2020:09:41:58 -0500] "POST /alerts HTTP/1.1" 200 0
10.0.x.x - - [03/Dec/2020:09:42:28 -0500] "POST /alerts HTTP/1.1" 200 0
10.0.x.x - - [03/Dec/2020:09:46:09 -0500] "POST /alerts HTTP/1.1" 200 0

**Comment by Bmannai** [comment]
Hello, 
I have the same problem, did you succeed to resolve this issue please ?

**Comment by maxwo** [comment]
Hello.
Can you try using the `./scripts/listen.sh` to launch an SNMPd server, and post here what it outputs?
Thank you.
