### ISSUE TITLE
Is there a way to have more than 5 distinct fields with the template?

### ISSUE THREAD

**Issue by JDA88** [maxwo/snmp_notifier#58]
No matter how I modify the template I can only change the value of the **.5** filed of the trap.
Is there a way to add **.6**, **.7** etc. values with additional fileds?
Ideally we would need sometiong like that
```
6:{{ $alert.Labels.instance }}
7:{{ $alert.Annotations.summary }}
8:{{ $alert.Annotations.custom1 }}
```

**Comment by maxwo** [comment]
As you can see in https://github.com/maxwo/snmp_notifier/blob/master/trapsender/trap_sender.go , only a few fields are sent. That may be a good idea to be able to send other fields as sub-elements, maybe using templates.
Can you describe your use-case a bit more?

**Comment by JDA88** [comment]
The issue we have it that the receiver needs the information’s splitted in different field to correctly format and handle the alert.
Ideally, we would need the instance, the severity and the message in 3 separate fields.
Using templates would be ideal yes.
