### ISSUE TITLE
Issue when trying to use snmp.trap-description-template

### ISSUE THREAD

**Issue by rn538e** [maxwo/snmp_notifier#6]
When I use the provided example for the snmp.trap-description-template

 --snmp.trap-description-template=\"\n{{- if (len .Alerts) gt 0 -}}\n{{- range $severity, $alerts := (groupAlertsByLabel .Alerts \"severity\") -}}\nStatus: {{ $severity }}\n{{- range $index, $alert := $alerts }}\n- Alert: {{ $alert.Labels.alertname }}\n  Summary: {{ $alert.Annotations.summary }}\n  Description: {{ $alert.Annotations.description }}\n{{ end }}\n{{ end }}\n{{ else -}}\nStatus: OK\n{{- end -}}\"

I get the following error when trying to load the YAML

# * : Invalid value: "The edited file failed validation": [yaml: line 37: did not find expected key, [invalid character 'a' looking for beginning of value, invalid character 'a' looking for beginning of value]]

I even tried loading the yaml in python and it seems to have an issue in column 180 which is around the s \"severity\") -}}\nStatus: {{ $severity  area.  Are you able to help me out with this please?

**Comment by maxwo** [comment]
Hey,
Indeed a strange behavior as this is the exact same template that is used as default. I'm gonna use a file to pass the template instead of inlining it on the command line, which actually would make more sense.
Thanks for your feedback.

**Comment by rn538e** [comment]
Got it to work with help from a colleague, had to enclose the whole arg in quotes and escape the quotes for the value, like this

"--snmp.trap-description-template=\"\n{{- if (len .Alerts) gt 0 -}}\n{{- range $severity, $alerts := (groupAlertsByLabel .Alerts \"severity\") -}}\nStatus: {{ $severity }}\n{{- range $index, $alert := $alerts }}\n- Alert: {{ $alert.Labels.alertname }}\n  Summary: {{ $alert.Annotations.summary }}\n  Description: {{ $alert.Annotations.description }}\n{{ end }}\n{{ end }}\n{{ else -}}\nStatus: OK\n{{- end -}}\""

**Comment by maxwo** [comment]
Good, although passing the template as a file is still a much better way to do this. I've prepared a branch with the feature: https://github.com/maxwo/snmp_notifier/tree/feat/description-in-file

**Comment by maxwo** [comment]
Just released the 0.3.0 version. Let me know if it fixes your issue.
