### ISSUE TITLE
groupAlertsByLable:wrong number of args for....

### ISSUE THREAD

**Issue by Sun55Kong** [maxwo/snmp_notifier#9]
hello ;
    this is a question when i execute ./snmp_notifier --..description-template.tpl
the Error : 
    502 bad Gateway:  err=template : description-template.tpl : 2:33:executeing "description-template.tpl"  at <groupAlertsByLabel>:wrong number of args for groupAlertsByLabel :want 2 got 0  . ......
this string  "groupAlertsByLabel" is changed?

**Comment by maxwo** [comment]
Hello,
Could you provide the template you are willing to use?
It seems some parameters are missing, but I cannot figure out which.
Thank you.

**Comment by wuhan1111** [comment]
Thank you for your reply,
you are right , missing a " "(space) in "groupAlertsByLabel  .Alerts" 
I want to know how to edit the template.tpl ,is it necessary for me to learn golang?

**Comment by maxwo** [comment]
Actually, you just need to know the golang template syntax (https://golang.org/pkg/text/template/), which should be enough to custom trap descriptions, providing conditions, loops and such.

To go slightly further, I'm using 2 custom directives: GroupAlertsByLabel and GroupAlertsByName (which is basically a group by the `alertname` label).

I should add a small documentation for them, may be useful.
