### ISSUE TITLE
Is an IPv6 target supported?

### ISSUE THREAD

**Issue by pcuzner** [maxwo/snmp_notifier#91]
I'm trying to use 1.2.1 with an ipv6 enabled snmptrapd target and can't get the notifier to send traps to the ipv6 address.

I've tried --snmp.destination=[fe80::250:56ff:fe83:e581]:162
 log shows: level=error msg="502 Bad Gateway: err=dial udp [fe80::250:56ff:fe83:e581]:162: connect: invalid argument

--snmp.destination=udp6:[fe80::250:56ff:fe83:e581]:162
fails "too colons in address"

likewise for tcp6[fe80::250:56ff:fe83:e581]:162

All the tests in the code appear to be IPv4 only - so is ipv6 to the snmp destination supported?

**Comment by maxwo** [comment]
There is no IPv6 support for destinations right now. It should work on IPv6 is your IP is behind a hostname or something, but you cannot give a plain IPv6 address in the command-line.

**Comment by maxwo** [comment]
I did more tests, and it appears all you have to do is providing this IPv6 address that way:

```
./snmp_notifier '--snmp.destination=[2a01:cb0c:474:1200:81d7:95dc:cbe7:1a39]:162'
```

I could successfully transmit a trap that way.

Can you confirm or give me more details?
