### ISSUE TITLE
422 Unprocessable Entity:

### ISSUE THREAD

**Issue by xueyilong** [maxwo/snmp_notifier#94]
Hi
Install 1.1.1 and 1.2.1 on centos7.9 , all get error logs when input https://xxx.xxx.xxx.xxx/alerts

level=error msg="422 Unprocessable Entity: err=EOF data=&{Receiver: Status: Alerts:[] GroupLabels:map[] CommonLabels:map[] CommonAnnotations:map[] ExternalURL:}" source="http_server.go:129"

How to slove it

**Comment by oliealex** [comment]
Hi,

Did you find a solution? I'm currently having the same issue.

**Comment by xueyilong** [comment]
It works well even when there is a problem, so you can ignore it

**Comment by maxwo** [comment]
Hi,
I couldn't reproduce your case. Can you still give me more details?
